#!/usr/bin/env bash

# This script creates a new tmux session with the provided name and
# creates two windows. The first window contains a zsh shell with
# the provided path (dir) opened. The second window has two panes
# pane 1 is neovim, potentially with an open file if one is provided
# and pane 2 with a zsh shell.

session_name=$1
dir=$2
file=$3
line=$4
tmux new-session -d -s "$session_name"
tmux new-window -t "${session_name}:2"
tmux send-keys -t "${session_name}:1" "cd ${dir}" C-m C-l
tmux send-keys -t "${session_name}:2" "cd ${dir}" C-m C-l
if [[ $file == "" ]]; then
	tmux send-keys -t "${session_name}:2" "nvim" C-m
else
	tmux send-keys -t "${session_name}:2" "nvim +${line} $file" C-m
fi
tmux split-window -h -d -t "${session_name}:2"
tmux resize-pane -t "${session_name}:2.2" -R 30
# the C-l is for the prompt logic for extra newline since after
# executing the cd... command there would be an extra newline
tmux send-keys -t "${session_name}:2.2" "cd ${dir}" C-m C-l