#!/usr/bin/env bash

# This script creates a new window for an existing session, opens
# the folder provided and starts lazygit

session_name=$1
dir=$2
tmux new-window -t "${session_name}:3"
tmux send-keys -t "${session_name}:3" "cd ${dir}" C-m C-l
tmux send-keys -t "${session_name}:3" "lazygit" C-m