#!/usr/bin/env bash

# This script creates a new window for an existing session, opens
# the folder provided and starts lazygit

session_name=$1
dir=$2
tmux new-window -t "${session_name}:3" -c "$dir"
# Send the C-l first to get rid of the double command displayed
tmux send-keys -t "${session_name}:3" C-l "lazygit" C-m