#!/usr/bin/env bash

project_type=$1
base_dir="${HOME}/dev/${project_type}/tmp"
template_dir="${HOME}/.templates/${project_type}"
next_num="001"
mkdir -p "$base_dir"
cd "$base_dir"

highest_num=$(find . -maxdepth 1 -type d -regex './[0-9][0-9][0-9]' \
	| sed 's|./||' \
	| sort -n \
	| tail -n 1
)

[ -n "$highest_num" ] && next_num=$(printf "%03d" $((10#$highest_num + 1)))

new_proj="${base_dir}/${next_num}"
mkdir -p "$new_proj"

cp -r "${template_dir}/"* "${new_proj}/"

session_name="~${new_proj#"$HOME"}"

case "$project_type" in
	go)
		create-project-windows $session_name $new_proj "${new_proj}/cmd/main.go" "4"
		;;
	c)
		create-project-windows $session_name $new_proj "${new_proj}/main.c" "3"
	  ;;
*)
	exit 0
	;;
esac

tmux switch-client -t "${session_name}:2"