#!/usr/bin/env bash

session_name=$(
	tmux list-sessions -F '#{session_name}' | \
	fzf \
		--tmux 85% \
		--ansi \
		--keep-right \
		--reverse \
		--preview-window=70% \
		--color='bg:#292C34' \
		--style=full \
		--list-label='sessions' \
		--preview " \
			tmux capture-pane -pe -S 0 \
			-E "$(tmux display-message -p '#{pane_height}')" \
			-t \"\$(tmux list-panes -t {} -F '#{pane_id}' -f '#{?pane_active,1,0}')\" \
			| cut -c -\$(tput cols)
		" \
		--bind="ctrl-x:execute-silent(tmux kill-session -t {})+clear-query+reload(tmux list-sessions -F '#{session_name}')"
) || exit 0

tmux switch-client -t "$session_name"